m = int(input('Diga uma número: '))
print('Taboada do {}'.format(m))
print(12*'-')
print('{} *  1 = {:2}'.format(m,1*m))
print('{} *  2 = {:2}'.format(m,2*m))
print('{} *  3 = {:2}'.format(m,3*m))
print('{} *  4 = {:2}'.format(m,4*m))
print('{} *  5 = {:2}'.format(m,5*m))
print('{} *  6 = {:2}'.format(m,6*m))
print('{} *  7 = {:2}'.format(m,7*m))
print('{} *  8 = {:2}'.format(m,8*m))
print('{} *  9 = {:2}'.format(m,9*m))
print('{} * 10 = {:2}'.format(m,10*m))
print(12*'-')
